Repository JobQuest/jobquest-fe, pull requests merged in 2021-02, with the labels that each got.

#7 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#8 Fe/feature/component structure setup
  cypress/integration/actions.spec.ts
  package-lock.json
  package.json
  src/App.scss
  src/App.tsx
  src/apiCalls.tsx
  src/index.tsx
  src/modules/App/App.scss
  src/modules/App/App.test.tsx
  src/modules/App/index.tsx
  src/modules/Common/Menu.tsx
  src/modules/Common/MenuItem.scss
  src/modules/Common/MenuItem.tsx
  src/modules/HomePage/index.tsx
  src/modules/Quest/index.tsx
  src/modules/QuestsList/index.tsx
  src/modules/User/Profile.scss
  src/modules/User/index.tsx
  src/modules/UserQuestLog/index.tsx
  src/routes/index.tsx
  src/routes/user.tsx
  src/ui/ActionButton/ActionButton.tsx
  src/ui/Button/Button.tsx
  src/ui/Grid/Grid.scss
  src/ui/Grid/Grid.tsx
Labels: React/TypeScript, enhancement, front end, sprint1

#19 Adjust tsconfig file
  tsconfig.json
Labels: chore, front end

#20 Fe/feature/quest log display
  src/apiCalls.tsx
  src/assets/Extras/Hero.png
  src/modules/App/index.tsx
  src/modules/User/Profile.scss
  src/modules/User/index.tsx
  src/modules/UserQuestLog/QuestLog.scss
  src/modules/UserQuestLog/index.tsx
Labels: CSS/SASS, React/TypeScript, enhancement, front end, sprint2

#21 Fe/feature/user quests
  cypress/integration/AvailableQuests.spec.ts
  cypress/integration/Quest.spec.ts
  public/index.html
  src/apiCalls.tsx
  src/assets/Action Cards/ActionCard_1.png
  src/assets/Action Cards/ActionCard_1_Hover.png
  src/assets/Action Cards/ActionCard_2.png
  src/assets/Action Cards/ActionCard_2_Hover.png
  src/assets/Hero/Hero_Idle.png
  src/assets/Hero/Monster_Attack.png
  src/index.scss
  src/interfaces.tsx
  src/logo.svg
  src/modules/App/App.scss
  src/modules/App/index.tsx
  src/modules/Common/Menu.tsx
  src/modules/Common/MenuItem.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/QuestList.scss
  src/modules/QuestsList/QuestsList.scss
  src/modules/QuestsList/index.tsx
  src/modules/test_assets/mock_data.tsx
  src/modules/test_assets/test_monster.png
  src/styles/_mixins.scss
Labels: CSS/SASS, React/TypeScript, enhancement, front end, sprint2

#22 Fe/feature/tabs and background styling
  cypress/integration/AvailableQuests.spec.ts
  cypress/integration/Quest.spec.ts
  cypress/integration/QuestLog.spec.ts
  cypress/integration/UserProfile.spec.ts
  package-lock.json
  src/apiCalls.tsx
  src/assets/Backgrounds/Background.png
  src/modules/App/App.scss
  src/modules/App/index.tsx
  src/modules/Common/MenuItem.tsx
  src/modules/HomePage/HomePage.scss
  src/modules/HomePage/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/QuestsList.scss
  src/modules/User/Profile.scss
  src/modules/User/index.tsx
  src/modules/UserQuestLog/QuestLog.scss
  src/modules/UserQuestLog/index.tsx
  src/routes/user.tsx
Labels: CSS/SASS, React/TypeScript, Testing, front end

#23 Fe/feature/quest encounters
  src/apiCalls.tsx
  src/interfaces.tsx
  src/modules/App/index.tsx
  src/modules/HomePage/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/index.tsx
  src/modules/User/index.tsx
  src/modules/UserQuestLog/index.tsx
Labels: React/TypeScript, enhancement, front end, sprint 3, sprint2
