Repository JobQuest/jobquest-fe, pull requests merged in 2021-03, with the labels that each got.

#27 Fe/fix/quests encounter
  src/interfaces.tsx
  src/modules/App/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/index.tsx
Labels: React/TypeScript, Refactoring, bug, front end, sprint 4

#32 Fe/fix/available quests error handling
  src/assets/Hero/Hero_Attack_1.png
  src/assets/Hero/Hero_Idle.png
  src/interfaces.tsx
  src/modules/App/index.tsx
  src/modules/Common/SpriteAnimation.tsx
  src/modules/HomePage/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/QuestsList.scss
  src/modules/QuestsList/index.tsx
  src/modules/User/Profile.scss
  src/modules/User/index.tsx
  src/modules/UserQuestLog/index.tsx
Labels: CSS/SASS, React/TypeScript, enhancement, extension, front end, sprint 4

#33 Fe/feature/buttons
  src/assets/Action Cards/ActionCard_1.png
  src/assets/Action Cards/ActionCard_1_Hover.png
  src/assets/Action Cards/ActionCard_2.png
  src/assets/Action Cards/ActionCard_2_Hover.png
  src/assets/Action Cards/Secondary/ActionCard_1.png
  src/assets/Action Cards/Secondary/ActionCard_1_Hover.png
  src/assets/Action Cards/Secondary/ActionCard_2.png
  src/assets/Action Cards/Secondary/ActionCard_2_Hover.png
  src/assets/Extras/Green_Button.png
  src/assets/Extras/Green_Button_Pressed.png
  src/assets/Extras/Red_Button.png
  src/assets/Extras/Red_Button_Pressed.png
  src/assets/Extras/Trophy.png
  src/assets/Extras/Window.png
  src/interfaces.tsx
  src/modules/App/index.tsx
  src/modules/HomePage/HomePage.scss
  src/modules/HomePage/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/index.tsx
  src/modules/User/index.tsx
  src/modules/UserQuestLog/index.tsx
Labels: CSS/SASS, React/TypeScript, Refactoring, enhancement, front end

#34 Add text and aria labels to fix Accessibility score
  src/modules/App/App.scss
  src/modules/App/index.tsx
  src/modules/HomePage/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/Quest/index.tsx
  src/modules/QuestsList/QuestsList.scss
  src/modules/QuestsList/index.tsx
  src/modules/User/Profile.scss
  src/modules/UserQuestLog/QuestLog.scss
  src/modules/UserQuestLog/index.tsx
Labels: CSS/SASS, React/TypeScript, front end, sprint 4

#35 Fe/feature/auth0
  .env
  package-lock.json
  package.json
  src/apiCalls.tsx
  src/index.tsx
  src/interfaces.tsx
  src/modules/App/index.tsx
  src/modules/Auth/Auth.scss
  src/modules/Auth/index.tsx
  src/modules/Common/LoginButton.tsx
  src/modules/Common/LogoutButton.tsx
  src/modules/Quest/index.tsx
  src/modules/User/Profile.scss
  src/modules/User/index.tsx
  src/modules/UserQuestLog/QuestLog.scss
  src/modules/UserQuestLog/index.tsx
Labels: React/TypeScript, bug, enhancement, front end, sprint 4

#36 Fix bug with user xp and monster hearts
  src/modules/App/index.tsx
  src/modules/Quest/Quest.scss
  src/modules/User/index.tsx
Labels: bug, front end, sprint 4

#39 Fe/feature/book cover
  src/assets/Backgrounds/BookCover.png
  src/modules/Auth/Auth.scss
  src/modules/Auth/index.tsx
  src/modules/Common/LoginButton.tsx
Labels: CSS/SASS, enhancement, front end

#40 Fe/test/cypress
  .env
  cypress.env.json
  cypress.json
  cypress/integration/AvailableQuests.spec.ts
  cypress/integration/Quest.spec.ts
  cypress/integration/QuestLog.spec.ts
  cypress/integration/UserProfile.spec.ts
  cypress/integration/actions.spec.ts
  cypress/support/commands.js
  src/modules/Auth/index.tsx
  src/modules/Common/LoginButton.tsx
  src/modules/Common/LogoutButton.tsx
  src/modules/HomePage/index.tsx
  src/modules/User/index.tsx
  src/modules/UserQuestLog/index.tsx
Labels: Refactoring, Testing, bug

#41 Fe/fix/bugs and style
  public/favicon.ico
  src/assets/Extras/Logo_jq.png
  src/modules/App/index.tsx
  src/modules/Auth/Auth.scss
  src/modules/Auth/index.tsx
  src/modules/Quest/index.tsx
Labels: React/TypeScript, bug, front end, sprint 4
